spring:
  kafka:
    bootstrap-servers:
      - broker:29092
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
server:
  port: 8080