CREATE DATABASE inventory;

CREATE TABLE store_items (
  id int NOT NULL,
  quantity int NOT NULL DEFAULT '0',
  modifiedtimestamp timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
